baseurl = "https://popovstefan.github.io/stefan-coder/"
title = "Stefan Popov / Стефан Попов"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"


[pagination]
pagerSize = 20

[markup.highlight]
style = "github-dark"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]
  author = "Stefan Popov"
  info = "Machine-Learning Engineer"
  description = "Stefan Popov's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  #gravatar = "john.doe@example.com"
  favicon = "favicon.ico"
  favicon_32 = "favicon-32x32.png"
  favicon_16 = "favicon-16x16.png"

  since = 2026

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/popovstefan/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/popovstefan/"
[[params.social]]
  name = "RSS"
  icon = "fa-solid fa-rss fa-2x"
  weight = 4
  url = "index.xml"
  rel = "alternate"
  type = "application/rss+xml"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Experience"
  weight = 2
  url  = "experience/"
[[menu.main]]
  name = "About"
  weight = 3
  url = "about/"